name: "Post message to xroute"
description: "Posts JSON data to a specified URL with OIDC token"

inputs:
  url:
    description: "The URL to send the data for xroute"
    required: true
  message:
    description: "The message to send"
    required: true
  path:
    description: "The path to the file to send"
    required: false
    default: "/msg/github/actions"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Commit SHA
      shell: bash
      id: sha
      run: echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Get OIDC Token
      id: token
      run: |
        ID_TOKEN=$(curl -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" ${ACTIONS_ID_TOKEN_REQUEST_URL} -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
        echo "id_token=${ID_TOKEN}" >> $GITHUB_ENV

    - name: Send JSON data via POST
      uses: actions/github-script@v6
      with:
        script: |
          const fetch = require('node-fetch');
          const url = `${{ inputs.url }}`;
          const commitSHA = process.env.commit_sha;
          const message = `${{ inputs.message }}`;
          const idToken = ${{ steps.token.outputs.result }};

          const response = await fetch(url + ${inputs.path}, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${idToken}`
            },
            body: JSON.stringify({
              commit_sha: commitSHA,
              message: message,
            })
          });

          if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Request failed with status ${response.status}: ${errorText}`);
          }

          console.log('Request successful!');
